# Generated by Django 5.2.1 on 2025-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='nif',
            field=models.CharField(max_length=12),
        ),
    ]
